name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Byt till din huvudgren om den heter något annat

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Om HTML-filerna ligger i root, annars ange mappen

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2